#!/bin/sh
. "$(dirname "$0")/husky.sh"

HUSKY_SKIP_HOOK="false"
echo "Initial HUSKY_SKIP_HOOK value: $HUSKY_SKIP_HOOK"

# Load environment variables from .env file
env_file="$(dirname "$0")/../.env.development.local"
if [ -f "$env_file" ]; then
    echo "Reading HUSKY_SKIP_HOOK from ${env_file}"
    while IFS='=' read -r key value; do
        # Check if the line contains the DISABLE_HUSKY variable
        if [ "$key" = "HUSKY_SKIP_HOOK" ]; then
            echo "Found key: $key, with value: $value"
            HUSKY_SKIP_HOOK=$(echo "$value" | tr -d '\r') 
            echo "HUSKY_SKIP_HOOK=$HUSKY_SKIP_HOOK"
            break  # Exit the loop once found
        fi
    done < "$env_file"
else
  echo "No .env.development.local file found"
fi

echo "Final HUSKY_SKIP_HOOK value: $HUSKY_SKIP_HOOK"

# Check if the HUSKY_SKIP_HOOK environment variable is set to true
if [ "$HUSKY_SKIP_HOOK" = "true" ]; then
  echo "Husky hooks are DISABLED"
  exit 0
else
echo "Husky hooks are ENABLED"
fi

echo "Running ESLint..."
npm run lint
lint_exit_code=$?

echo "Running Prettier..."
npm run prettier
prettier_exit_code=$?

if [ $lint_exit_code -ne 0 ]; then
echo "ESLint failed. Please fix the issues before committing."
exit 1
fi

if [ $prettier_exit_code -ne 0 ]; then
echo "Prettier failed. Please fix the issues before committing."
exit 1
fi

echo "All checks passed. Proceeding with commit."
